### ISSUE TITLE
Why do you use a rather old preact-compat version?

### ISSUE THREAD

**Issue by manuschillerdev** [developit/nextjs-preact-demo#8]
Hey!

I noticed, that you explicitly use a rather outdated preact-compat version. Is there any reason, why you didn't chose a current preact x version?

https://github.com/developit/nextjs-preact-demo/blob/master/package.json#L13

Thanks! :)

**Comment by JoviDeCroock** [comment]
This isn't the preact-compat you normally know from npm, this is a github dependency. The name might be confusing yes

https://github.com/preact-compat

**Comment by manuschillerdev** [comment]
@JoviDeCroock thanks.

Not sure I am understanding this yet.
When I use preact compact, I alias react to compat from the regular `preact/compat` package like so:

```
"resolve": { 
    "alias": { 
      "react": "preact/compat",
      "react-dom/test-utils": "preact/test-utils",
      "react-dom": "preact/compat",
    },
  }
```


The package `github.com/preact-compat/react` used here in `nextjs-preact-demo` 
 seems to be rather outdated:

<img width="998" alt="Bildschirmfoto 2020-04-09 um 09 40 08" src="https://user-images.githubusercontent.com/56154253/78870499-840d8780-7a46-11ea-9f4e-a89a5ae3fd5f.png">

So to me it remains unclear why this github dependency was used for such a "bleeding edge" nextjs example. Just curious! :) 

Thanks!

**Comment by developit** [comment]
@manuschillerdev the package used as an alias here is itself just an alias. It is a "proxy package" that just imports `preact/compat` and re-exports it:

<a href="https://github.com/preact-compat/react/blob/1.x/index.js"><img src="https://user-images.githubusercontent.com/105127/79159179-9f112c00-7da5-11ea-8dc7-02a882679ea0.png" width="300"></a>

This is necessary because npm aliases _(the aliasing technique in use here)_ don't support subpackages (paths within packages). That meant I couldn't alias `react` directly to `preact/compat` (the compat directory inside the preact package). Instead, I aliased it to the `preact-compat/react` _package_, which just re-exports `preact/compat`.

It's convoluted and may be unnecessary if you copy [this change](https://github.com/developit/nextjs-preact-demo/commit/f31d1dd6bbcf0d1392913274101a2af487e0b8c2).

**Comment by developit** [comment]
Closing for now since this might mislead folks, but I think ultimately the "fix" here is to not use npm aliases. They're nice and minimal in terms of setup, but probably confusing for updates. They also don't apply to transient dependencies, which has been causing issues for folks.

**Comment by manuschillerdev** [comment]
thanks! that cleared things up for me @developit 
Sorry for the confusion @JoviDeCroock 😄
